(define (problem depot-3-2-2-5-6-13) (:domain depots)
(:objects
	depot0 depot1 depot2 - Depot
	distributor0 distributor1 - Distributor
	truck0 truck1 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - Hoist)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 depot1)
	(clear crate12)
	(at pallet2 depot2)
	(clear crate9)
	(at pallet3 distributor0)
	(clear crate6)
	(at pallet4 distributor1)
	(clear crate10)
	(at truck0 distributor1)
	(at truck1 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 depot1)
	(available hoist5)
	(at crate0 distributor0)
	(on crate0 pallet3)
	(at crate1 depot2)
	(on crate1 pallet2)
	(at crate2 distributor0)
	(on crate2 crate0)
	(at crate3 distributor0)
	(on crate3 crate2)
	(at crate4 distributor0)
	(on crate4 crate3)
	(at crate5 distributor0)
	(on crate5 crate4)
	(at crate6 distributor0)
	(on crate6 crate5)
	(at crate7 depot2)
	(on crate7 crate1)
	(at crate8 depot2)
	(on crate8 crate7)
	(at crate9 depot2)
	(on crate9 crate8)
	(at crate10 distributor1)
	(on crate10 pallet4)
	(at crate11 depot1)
	(on crate11 pallet1)
	(at crate12 depot1)
	(on crate12 crate11)
)

(:goal (and
		(on crate0 crate11)
		(on crate1 crate7)
		(on crate2 pallet1)
		(on crate4 pallet4)
		(on crate5 pallet3)
		(on crate7 crate2)
		(on crate8 pallet0)
		(on crate9 crate8)
		(on crate11 crate4)
		(on crate12 pallet2)
	)
))
